### ISSUE TITLE
Add Support For ContainerD

### ISSUE THREAD

**Issue by jkattmann** [hharnisc/kubescope-cli#3]
This works great on a default AKS deployment in azure but I get the following errors on a custom cluster using containerd for the runtime.

```λ  kubectl logs -n xd-citadel kubescope-cli-example

> kubescope-cli@0.0.1 start /usr/src/app
> node .

Error: Parse Error
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Parse Error
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubescope-cli@0.0.1 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubescope-cli@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-23T17_42_32_450Z-debug.log
```

I did change the volume mount to:
```volumes:
  - name: docker-sock-volume
    hostPath:
      path: /run/containerd/containerd.sock
```

**Comment by hharnisc** [comment]
I haven't tried it with containerd yet! But this would be a great addition 😀
